// Common 5-letter German words used as the daily-answer pool.
// Extend freely — Wordle game accepts any 5-letter input regardless of this list.

export const DE_WORDS: string[] = [
  "abend","acker","adler","affen","affe","aktiv","alarm","algen","alpha","altar",
  "anker","apfel","april","arbeit","arena","arme","armee","atmen","atom","auge",
  "augen","autor","autos","backen","baden","bahn","baker","balken","balten","bande",
  "bange","banken","baron","barre","beben","beete","beere","beigen","beine","beize",
  "berge","beten","beton","biber","biene","bilde","bilder","binde","blase","blau",
  "blech","blick","blitz","blume","boden","boote","bord","brake","brand","braten",
  "braun","brave","bremse","brett","brief","brot","bruch","brunn","buch","buden",
  "bulle","bunte","burg","busse","creme","dach","damen","danke","datei","daten",
  "deich","decke","denken","derbe","dicht","dicke","diele","ding","dose","drall",
  "drama","draht","draus","drei","drink","dritt","dunst","durch","ebbe","ebene",
  "edler","ehren","ehrlich","eiche","eichen","eilig","einig","eisen","eitel","eklat",
  "elend","elite","engel","ente","enten","ernte","erst","essen","euter","fabel",
  "faden","fahne","faktor","falke","falle","faltt","faser","faust","feder","feier",
  "feind","feist","felsen","ferne","feste","feuer","fieber","figur","filme","filter",
  "finger","firma","fisch","fjord","flach","fleck","flieg","flink","flora","flotte",
  "flott","flott","forst","frage","frank","frech","freie","freund","friede","frisch",
  "frost","frucht","fuchs","fuge","funke","futur","gabe","gabel","galle","ganze",
  "garde","garn","garten","gasse","gebot","gegen","geige","geist","gelb","geld",
  "gerne","gesicht","gesund","gewalt","gips","glanz","glaub","glanz","glock","glueck",
  "gnade","gold","gott","grad","grade","graf","gramm","grass","grenze","grobe",
  "grund","gruppe","gummi","gunst","haar","habe","hafen","hain","haken","halbe",
  "halle","halt","hamster","hand","hang","harf","hase","haufe","heer","hefe",
  "heft","heim","heiss","heizung","helfen","hell","hemd","henne","herbst","herde",
  "herr","herz","heute","himmel","hirsch","hocker","hoehe","hohe","horst","hotel",
  "huehn","hund","hunde","hunger","hut","ideal","idee","igel","immer","insel",
  "jacke","jagd","jahr","jahre","junge","jung","kabel","kaese","kaffe","kahn",
];
