// Common 5-letter French words used as the daily-answer pool.
// Extend freely — Wordle game accepts any 5-letter input regardless of this list.

export const FR_WORDS: string[] = [
  "abord","acide","acier","actes","admis","adore","adule","afins","agile","aigle",
  "aigre","aimer","ainsi","aller","alors","amine","amour","ample","ancre","ange",
  "anges","angle","anime","annee","apres","arbre","argent","armer","artie","aubes",
  "auteur","avant","avale","avant","avenir","avion","avoir","azure","bacle","bagne",
  "bagne","baies","balle","banal","bande","banni","barre","basse","bassin","bavard",
  "beans","beauf","beaux","bebe","bedon","beige","bequille","berge","bichon","biche",
  "bidon","biere","bilan","biere","blanc","blese","bleus","bloc","blond","bobos",
  "boire","bombe","bonde","bonus","bord","botte","bouge","boule","bourg","bouts",
  "boxer","brave","brise","bronze","brusque","brute","buche","budget","cable","cabri",
  "cache","cadre","cafes","cage","caisse","calme","camp","canal","canard","candide",
  "canal","canot","capot","carat","caree","carre","cartes","casse","catch","cause",
  "cavale","celui","cense","cerise","cesar","cesse","chaque","chant","charge","charme",
  "chats","chaud","chef","chien","chiffe","choix","cible","cidre","ciel","cigare",
  "cinq","cite","civil","claie","clair","clame","clan","clarte","clef","client",
  "cloue","clous","clown","coach","cobra","cocon","code","coeur","coffre","cogito",
  "coin","colle","comme","compte","conte","corde","corps","cote","coton","couche",
  "coude","couler","coupe","cours","court","crabe","crane","crayon","creme","creuse",
  "criee","crier","crime","crois","croix","cuir","cuivre","culte","curie","cycle",
  "dame","danse","date","debut","decor","defi","degat","dela","delta","dense",
  "depart","desire","deuil","devant","devoir","diable","digne","dindon","dire","dispo",
  "divers","docte","doigt","donne","donner","dorme","dort","douce","douche","douze",
  "drame","drap","drole","duree","durer","duvet","echec","ecole","ecran","ecrire",
  "edify","effet","egale","egard","eglise","elite","email","emane","emoi","empile",
  "encart","encre","enfance","engin","enjeu","ennui","entre","envie","epice","epine",
  "epoux","epuis","erres","esora","essai","etage","etant","ether","etoile","etude",
  "evade","exact","exige","extra","fable","face","facon","faible","faire","faisan",
];
