// Common 5-letter Dutch words used as the daily-answer pool.
// Extend freely — Wordle game accepts any 5-letter input regardless of this list.

export const NL_WORDS: string[] = [
  "appel","banaan","bijna","blauw","boven","brand","breed","broek","bruin","buurt",
  "deals","derde","dicht","draad","draai","drank","droom","duwen","eenig","enkel",
  "extra","fabel","fabriek","feest","feiten","felle","fluit","fonds","ganse","gauwe",
  "geest","gezin","glans","goede","graag","graas","groot","handel","hartig","hechte",
  "hoger","hoofd","huren","ijzer","ijver","jacht","jacht","jagen","jurk","kaart",
  "kabel","klant","klein","kleur","klimt","klont","klopt","koers","koets","komen",
  "korte","kraan","krijg","kunst","laagt","laars","ladie","lafje","laken","langs",
  "laten","lange","laxer","lekke","lelie","leren","leven","liefd","liggen","linde",
  "logge","lopen","macht","maken","markt","maten","meent","merkt","meten","mijne",
  "milde","modus","moeit","moeit","molen","mooie","morgen","muziek","nacht","neder",
  "neust","niets","nodig","norse","noten","nuchter","oever","onder","onkel","oogje",
  "open","optie","oranje","ouder","over","paard","plant","plaat","plein","ploeg",
  "poort","pover","prijs","prima","punten","raken","reeks","regel","reize","reken",
  "remmen","reuze","rijke","ronde","ruige","ruime","sabel","schat","schol","schop",
  "schub","schut","slaap","slaag","slang","sloep","slope","sluit","snijd","snor",
  "spook","sport","steek","steen","steil","stelt","sterk","stier","stijf","stoer",
  "stomp","storm","straf","stuk","stuur","tafel","talen","tasje","teder","tegen",
  "teken","thuis","tijger","toeval","trots","trouw","tussen","twijfel","uiten","vader",
  "vakje","vaste","veder","veelt","veld","venst","verre","vinden","vlees","vlieg",
  "voeren","volgen","vorig","vraag","vrede","vreemd","vroeg","vrouw","waard","wacht",
  "wagen","waren","weer","wegen","wenst","werk","wereld","wezen","wijde","winst",
  "witte","woest","wonen","woord","zacht","zaden","zalig","zee","zeker","zelfd",
  "zenuw","zicht","ziel","zilver","zingen","zitje","zoeken","zoete","zomer","zonde",
  "zorgen","zwaar","zwart","zwemt","akker","amper","balke","balsa","bange","baron",
  "barre","beans","bedde","beeld","bekers","beste","beten","biefs","bijna","blank",
  "bloed","bocht","bodem","boete","bord","boten","brave","breken","brein","broze",
];
