import type { Locale } from "./i18n";
import enSolutions from "@/data/wordlists/en/solutions.json";
import nlSolutions from "@/data/wordlists/nl/solutions.json";
import deSolutions from "@/data/wordlists/de/solutions.json";
import frSolutions from "@/data/wordlists/fr/solutions.json";
import esSolutions from "@/data/wordlists/es/solutions.json";
import ptBrSolutions from "@/data/wordlists/pt-BR/solutions.json";

// Locale → frequency-ranked, slur-filtered, deterministically shuffled
// daily-answer pool. Generated by scripts/generate-wordlists.mjs from
// hermitdave/FrequencyWords (OpenSubtitles 2018, CC BY-SA 4.0)
// intersected with wooorm/dictionaries (MIT) hunspell base forms.
//
// hi/ja have no Latin-script wordlist of their own — they share the en
// pool, mirroring how their keyboards already use Latin letters. Same
// fallback the codebase used before this module was generated.
const POOLS: Record<Locale, readonly string[]> = {
  en: enSolutions,
  nl: nlSolutions,
  de: deSolutions,
  fr: frSolutions,
  es: esSolutions,
  "pt-BR": ptBrSolutions,
  hi: enSolutions,
  ja: enSolutions,
};

export function dayIndex(date: Date = new Date()): number {
  // UTC days since epoch — same value for everyone on the same calendar day in UTC.
  return Math.floor(date.getTime() / 86_400_000);
}

export function dailyWord(locale: Locale, date: Date = new Date()): string {
  const pool = POOLS[locale];
  const idx = dayIndex(date) % pool.length;
  return pool[idx];
}

export function randomWord(locale: Locale): string {
  const pool = POOLS[locale];
  return pool[Math.floor(Math.random() * pool.length)];
}

// Synchronous existence check against the per-locale solutions pool.
// Used by letterstack only as a soft hint (letterstack accepts the guess
// either way); the Wordle guess validator needs the wider GUESSES set,
// which is async — see lib/wordle/guesses.ts.
export function isInWordList(locale: Locale, word: string): boolean {
  const pool = POOLS[locale];
  return pool.includes(word.toLowerCase());
}
